---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Rosy Insights"
keywords:    "analytics, consulting, data science, data engineering, detection, data, autonomous, artifial intelligence, patterns, opportunities, measure, metrics, impact, customer profiling, revenue growth, strategy, product pricing, product marketing, explainable AI, action plans, leverage, machine learning, algorithms, performance tracking, customer mapping, optimization, promotional mix and spend, revenue boost, customer affinity, process efficiency"
description: "Rosy Insights derives intelligence from data that dashboards miss. Discover opportnities that you would haver known were there. Our purpose is to ensure analytics driven growth by unlocking the potential in your data. We deliver customized action plans based on your unique needs. We partner with you to create demosnstratable value for your customers. "
source_link: "https://xwatts.github.io/rosyinsights/"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#03588C'
  sea:     '#3999BF'
  orange:    '#F2A477'
  green:    '#468C32'
  salmon: '#F27457'

kramdown:
  auto_ids:  false
